JangoMailBundle_logs:
    pattern:  /logs
    defaults: { _controller: JangoMailBundle:Default:logs }
    
JangoMailBundle_home:
    pattern:  /
    defaults: { _controller: JangoMailBundle:Default:index }
    
JangoMailBundle_logs_view:
    pattern:  /logs/{id}
    defaults: { _controller: JangoMailBundle:Default:log }
    
JangoMailBundle_envio:
    pattern:  /probar
    defaults: { _controller: JangoMailBundle:Default:envio }

JangoMailBundle_Grupos_index:
    resource: "@JangoMailBundle/Resources/config/rutas/grupos.yml"
    prefix:  /grupos
