JangoMailBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: JangoMailBundle:Default:index }
    
JangoMailBundle_sendMass:
    pattern:  /send
    defaults: { _controller: JangoMailBundle:Default:send }
    
JangoMailBundle_agregarMiembros:
    pattern:  /add_members
    defaults: { _controller: JangoMailBundle:Default:agregarMiembros }

JangoMailBundle_Grupos:
    resource: "@JangoMailBundle/Resources/config/rutas/grupos.yml"
    prefix:  /grupos
