parameters:
    jango_mail_fos.class: Netpeople\JangoMailBundle\JangoMailFosUser
    jango_mail.class: Netpeople\JangoMailBundle\JangoMail
    jango_mail.campaign_sending.class: Netpeople\JangoMailBundle\CampaignSending
    jango_mail.transactional_sending.class: Netpeople\JangoMailBundle\TransactionalSending
    jango_mail.group_admin.class: Netpeople\JangoMailBundle\Groups\GroupAdmin
    jango_mail.campaign_reporting.class: Netpeople\JangoMailBundle\Reporting\CampaignReporting
    
    jango_mail.config:
          url_jango: http://api.jangomail.com/api.asmx?WSDL
          username: ~
          password: ~
          fromemail: ~
          fromname: ~
          transactional_group: ~

services:
    jango_mail:
        class: %jango_mail.class%
        arguments: [%jango_mail.config% , "@doctrine" ]
        calls:
            - [ setCampaign, [ "@jango_mail.campaign_sending" ] ]
            - [ setTransactional, [ "@jango_mail.transactional_sending" ] ]

    jango_mail.campaign_sending:
        class: %jango_mail.campaign_sending.class%
        arguments: ["@jango_mail"]

    jango_mail.transactional_sending:
        class: %jango_mail.transactional_sending.class%
        arguments: ["@jango_mail"]

    jango_mail.group_admin:
        class: %jango_mail.group_admin.class%
        arguments: ["@jango_mail"]

    jango_mail.campaign_reporting:
        class: %jango_mail.campaign_reporting.class%
        arguments: ["@jango_mail"]