parameters:
    jango_mail.config:
          url_jango: http://api.jangomail.com/api.asmx?WSDL
          username: ~
          password: ~
          fromemail: ~
          fromname: ~

services:
    jango_mail:
        class: Netpeople\JangoMailBundle\JangoMail
        arguments: [%jango_mail.config% , "@doctrine" ]
        calls:
            - [ setCampaign, [ "@jango_mail.campaign_sending" ] ]
            - [ setTransactional, [ "@jango_mail.transactional_sending" ] ]
            - [ setGroupAdmin, [ "@jango_mail.group_admin" ] ]

    jango_mail.campaign_sending:
        class: Netpeople\JangoMailBundle\CampaignSending
        arguments: ["@jango_mail"]
        public: false

    jango_mail.transactional_sending:
        class: Netpeople\JangoMailBundle\TransactionalSending
        arguments: ["@jango_mail"]
        public: false

    jango_mail.group_admin:
        class: Netpeople\JangoMailBundle\Groups\GroupAdmin
        arguments: ["@jango_mail"]
        public: false
