parameters:
    jango_mail.config:
          url_jango: http://api.jangomail.com/api.asmx?WSDL
          username: ~
          password: ~
          fromemail: ~
          fromname: ~
          transactional_group: ~
    jango_mail_fos.config:
        template:
            confirmation: %fos_user.registration.confirmation.template%
            resetting: %fos_user.resetting.email.template%
    from_email:
            confirmation: %fos_user.registration.confirmation.from_email%
            resetting: %fos_user.resetting.email.from_email%

services:
    jango_mail:
        class: Netpeople\JangoMailBundle\JangoMail
        arguments: [%jango_mail.config% , "@doctrine" ]
        calls:
            - [ setCampaign, [ "@jango_mail.campaign_sending" ] ]
            - [ setTransactional, [ "@jango_mail.transactional_sending" ] ]
            - [ setGroupAdmin, [ "@jango_mail.group_admin" ] ]

    jango_mail.campaign_sending:
        class: Netpeople\JangoMailBundle\CampaignSending
        arguments: ["@jango_mail"]

    jango_mail.transactional_sending:
        class: Netpeople\JangoMailBundle\TransactionalSending
        arguments: ["@jango_mail"]

    jango_mail.group_admin:
        class: Netpeople\JangoMailBundle\Groups\GroupAdmin
        arguments: ["@jango_mail"]
    
    jango_mail_fos:
        class: Netpeople\JangoMailBundle\JangoMailFosUser
        arguments: ["@mailer","@router","@twig",%jango_mail_fos.config%, "@?logger"]
        calls:
            - [ setCampaign, [ "@jango_mail.campaign_sending" ] ]
            - [ setTransactional, [ "@jango_mail.transactional_sending" ] ]
            - [ setGroupAdmin, [ "@jango_mail.group_admin" ] ]
