<?php

namespace Netpeople\JangoMailBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmailLogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailLogsRepository extends EntityRepository
{
    
}