<?php

namespace Netpeople\JangoMailBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * EmailLogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailLogsRepository extends EntityRepository
{
    public function getQueryAll($order = 'DESC')
    {
        return $this->createQueryBuilder('logs')
            ->orderBy('logs.id', $order)
            ;
    }
}